IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[COORDINATED_TASK_CLAIM]') AND TYPE IN (N'U'))
CREATE TABLE COORDINATED_TASK_CLAIM (
  TASK_NAME VARCHAR (512) NOT NULL,
  FIRE_KEY BIGINT NOT NULL DEFAULT -1,
  INCARNATION INT NOT NULL DEFAULT 1,
  OWNER_EPOCH BIGINT NOT NULL DEFAULT 0,
  OWNER_BOOT_ID VARCHAR (64),
  SCHEDULE_FP VARCHAR (128),
  DELETE_GUARD VARCHAR (64),
  TRIGGER_FAMILY VARCHAR (10),
  STATUS VARCHAR (10) NOT NULL DEFAULT 'OPEN',
  NODE_ID VARCHAR (512),
  CLAIMED_AT BIGINT,
  PRIMARY KEY NONCLUSTERED (TASK_NAME)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[NODE_ADVERTISEMENT]') AND TYPE IN (N'U'))
CREATE TABLE NODE_ADVERTISEMENT (
  GROUP_ID VARCHAR (512) NOT NULL,
  NODE_ID VARCHAR (512) NOT NULL,
  HEARTBEAT_WINDOW BIGINT NOT NULL,
  BOOT_ID VARCHAR (64) NOT NULL,
  BOOT_STARTED_AT BIGINT NOT NULL,
  ELIGIBILITY VARCHAR (16) NOT NULL DEFAULT 'PENDING',
  CONFIG_FINGERPRINT VARCHAR (512),
  UPDATED_AT BIGINT NOT NULL,
  PRIMARY KEY NONCLUSTERED (GROUP_ID, NODE_ID)
);
