CREATE TABLE COORDINATED_TASK_CLAIM (
    TASK_NAME VARCHAR2(512) NOT NULL,
    FIRE_KEY NUMBER(19) DEFAULT -1 NOT NULL,
    INCARNATION NUMBER(10) DEFAULT 1 NOT NULL,
    OWNER_EPOCH NUMBER(19) DEFAULT 0 NOT NULL,
    OWNER_BOOT_ID VARCHAR2(64),
    SCHEDULE_FP VARCHAR2(128),
    DELETE_GUARD VARCHAR2(64),
    TRIGGER_FAMILY VARCHAR2(10),
    STATUS VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
    NODE_ID VARCHAR2(512),
    CLAIMED_AT NUMBER(19),
    PRIMARY KEY (TASK_NAME)
);

CREATE TABLE NODE_ADVERTISEMENT (
    GROUP_ID VARCHAR2(512) NOT NULL,
    NODE_ID VARCHAR2(512) NOT NULL,
    HEARTBEAT_WINDOW NUMBER(19) NOT NULL,
    BOOT_ID VARCHAR2(64) NOT NULL,
    BOOT_STARTED_AT NUMBER(19) NOT NULL,
    ELIGIBILITY VARCHAR2(16) DEFAULT 'PENDING' NOT NULL,
    CONFIG_FINGERPRINT VARCHAR2(512),
    UPDATED_AT NUMBER(19) NOT NULL,
    PRIMARY KEY (GROUP_ID, NODE_ID)
);
